name = "Secret"
artist = "Drama Trial"
charter = "amyspark-ng"
initial_bpm = 180
initial_scrollspeed = 1
time_signature = [ 4, 4 ]
uuid_DONT_CHANGE = "be4c3897-5e37-4f93-81ab-e5262dbe11a5"
audio_file = "07 - drama trial - secret.ogg"
cover_file = "secret cover.jpg"